# Generated by Django 5.0.14 on 2026-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_phase3_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pipeline_stage',
            field=models.CharField(choices=[('new', 'Mới'), ('consulting', 'Đang tư vấn'), ('viewing', 'Đã hẹn xem'), ('negotiating', 'Đang thương lượng'), ('won', 'Đã chốt'), ('lost', 'Đã hủy')], default='new', max_length=24),
        ),
    ]
