# Generated by Django 6.0.3 on 2026-03-18 16:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Agent base location (lat/lng)', srid=4326),
        ),
    ]
