# Generated by Django 5.0.14 on 2026-03-20 16:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Agent base location (lat/lng)', srid=4326),
        ),
    ]
