# Generated by Django 5.0.14 on 2026-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='amenity_type',
            field=models.CharField(choices=[('school', 'Trường học'), ('hospital', 'Bệnh viện'), ('park', 'Công viên'), ('mall', 'Trung tâm thương mại'), ('supermarket', 'Siêu thị'), ('transport', 'Điểm giao thông'), ('other', 'Khác')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='property',
            name='listing_status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('active', 'Đang bán'), ('sold', 'Đã bán'), ('hidden', 'Ẩn tin')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Căn hộ'), ('house', 'Nhà'), ('land', 'Đất')], max_length=20),
        ),
    ]
