# Generated by Django 5.0.14 on 2026-03-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
